<?xml version="1.0"?>
<!DOCTYPE note[
<!ELEMENT note (to+,from,heading,body,payment)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT payment (#PCDATA)>
<!ATTLIST payment type CDATA #REQUIRED>
]>
<note>
    <to>

    </to>
    <to>

    </to>
    <from>
</from>
   <heading>
</heading>
    <body>
        
    </body>
    <payment type="missing"></payment>
</note>